apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hdmi-switch-zot-pull-secret
  namespace: hdmi-switch
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: hdmi-switch-zot-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {{`{"auths":{"registry.morrisons.site":{"username":"ci","password":"{{ .password }}","auth":"{{ printf "ci:%s" .password | b64enc }}"}}}`}}
  data:
    - secretKey: password
      remoteRef:
        key: homelab/hdmi-switch
        property: ZOT_CI_PASSWORD
