apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdmi-switch-ui
  namespace: hdmi-switch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdmi-switch-ui
  template:
    metadata:
      labels:
        app: hdmi-switch-ui
    spec:
      imagePullSecrets:
        - name: hdmi-switch-zot-pull-secret
      containers:
        - name: hdmi-switch-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          ports:
            - containerPort: 80
