apiVersion: v1
kind: ConfigMap
metadata:
  name: hdmi-switch-verify-script
  namespace: hdmi-switch
  annotations:
    argocd.argoproj.io/hook: PostSync
data:
{{- (.Files.Glob "scripts/*").AsConfig | nindent 2 }}
